import os
import json
import time
import queue
from flask import Flask, render_template, request, jsonify, Response, send_file, make_response
from fpdf import FPDF
from database import (
    init_db, get_soc_metrics, get_recent_events, get_event_by_id,
    get_reports, get_report_by_id, delete_report, get_setting, set_setting, get_db_connection
)
from ingestion import LogIngestionEngine, register_listener, unregister_listener
from groq_service import generate_incident_report, query_soc_assistant, AVAILABLE_MODELS, is_groq_configured

static_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static')
app = Flask(__name__, static_folder=static_dir)
app.config['SECRET_KEY'] = 'soc-ai-dashboard-secret-2026'

# Initialize DB & Ingestion Engine
init_db()
ingestion_engine = LogIngestionEngine()
ingestion_engine.start()

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/choco.jpg')
def serve_choco_root():
    img_path = r"C:\Users\wwwpr\.gemini\antigravity\brain\d6348fb3-9adf-4ddd-941d-a80d811ecf3d\choco_decent_mascot_1789627625626.jpg"
    return send_file(img_path, mimetype='image/jpeg')

@app.route('/static/choco.jpg')
def serve_choco_static():
    img_path = r"C:\Users\wwwpr\.gemini\antigravity\brain\d6348fb3-9adf-4ddd-941d-a80d811ecf3d\choco_decent_mascot_1789627625626.jpg"
    return send_file(img_path, mimetype='image/jpeg')

@app.route('/api/stats', methods=['GET'])
def api_stats():
    metrics = get_soc_metrics()
    metrics['groq_configured'] = is_groq_configured()
    metrics['simulator_active'] = ingestion_engine.simulator_enabled
    metrics['available_models'] = AVAILABLE_MODELS
    metrics['current_model'] = get_setting('groq_model', AVAILABLE_MODELS[0])
    return jsonify(metrics)

@app.route('/api/events', methods=['GET'])
def api_events():
    severity = request.args.get('severity', 'ALL')
    limit = int(request.args.get('limit', 50))
    events = get_recent_events(limit=limit, severity=severity)
    return jsonify(events)

@app.route('/api/events/<event_id>', methods=['GET'])
def api_event_detail(event_id):
    event = get_event_by_id(event_id)
    if not event:
        return jsonify({"error": "Event not found"}), 404
    return jsonify(event)

@app.route('/api/reports', methods=['GET'])
def api_reports():
    reports = get_reports(limit=100)
    return jsonify(reports)

@app.route('/api/reports/<report_id>', methods=['GET'])
def api_report_detail(report_id):
    report = get_report_by_id(report_id)
    if not report:
        return jsonify({"error": "Report not found"}), 404
    return jsonify(report)

@app.route('/api/reports/generate', methods=['POST'])
def api_generate_report():
    data = request.json or {}
    event_id = data.get('event_id')
    model_name = data.get('model')
    if not event_id:
        return jsonify({"error": "event_id is required"}), 400
    
    try:
        report = generate_incident_report(event_id, model_name=model_name)
        return jsonify(report)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/reports/<report_id>', methods=['DELETE'])
def api_delete_report(report_id):
    delete_report(report_id)
    return jsonify({"success": True, "message": f"Report {report_id} deleted."})

@app.route('/api/reports/<report_id>/pdf', methods=['GET'])
def api_download_report_pdf(report_id):
    report = get_report_by_id(report_id)
    if not report:
        return jsonify({"error": "Report not found"}), 404

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(220, 38, 38) # Red header
    pdf.cell(0, 10, "SECURITY INCIDENT ANALYSIS REPORT", ln=True, align="C")
    
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Generated by Groq SOC AI Analyst | Report ID: {report['report_id']}", ln=True, align="C")
    pdf.ln(5)

    # Metadata Table
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(0, 0, 0)
    pdf.set_fill_color(240, 240, 240)
    
    pdf.cell(45, 7, " Event Title:", border=1, fill=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(145, 7, f" {report.get('event_title', 'N/A')}", border=1, ln=True)
    
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(45, 7, " Severity / Category:", border=1, fill=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(145, 7, f" {report.get('event_severity', 'N/A')} | {report.get('event_category', 'N/A')}", border=1, ln=True)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(45, 7, " Source IP / Date:", border=1, fill=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(145, 7, f" {report.get('source_ip', 'N/A')} | {report['created_at']}", border=1, ln=True)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(45, 7, " MITRE ATT&CK Tag:", border=1, fill=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(145, 7, f" {report.get('mitre_attack', 'N/A')}", border=1, ln=True)
    pdf.ln(8)

    # Report Body Markdown Cleanup
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    
    lines = report['content_markdown'].split('\n')
    for line in lines:
        line_clean = line.encode('latin-1', 'replace').decode('latin-1')
        if line_clean.startswith('# '):
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(0, 8, line_clean.replace('# ', '').strip(), ln=True)
        elif line_clean.startswith('## '):
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(30, 58, 138)
            pdf.cell(0, 7, line_clean.replace('## ', '').strip(), ln=True)
        elif line_clean.startswith('### '):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(51, 65, 85)
            pdf.cell(0, 6, line_clean.replace('### ', '').strip(), ln=True)
        elif line_clean.startswith('- ') or line_clean.startswith('* '):
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 5, "  * " + line_clean[2:].strip())
        else:
            pdf.set_font("Helvetica", "", 10)
            if line_clean.strip():
                pdf.multi_cell(0, 5, line_clean.strip())
            else:
                pdf.ln(3)

    response = make_response(bytes(pdf.output()))
    response.headers['Content-Type'] = 'application/pdf'
    response.headers['Content-Disposition'] = f'attachment; filename="SOC_Report_{report["report_id"]}.pdf"'
    return response

@app.route('/api/assistant', methods=['POST'])
def api_assistant():
    data = request.json or {}
    query = data.get('query')
    history = data.get('history', [])
    model = data.get('model')
    
    if not query:
        return jsonify({"error": "Query string is required"}), 400
    
    res = query_soc_assistant(user_query=query, chat_history=history, model_name=model)
    return jsonify(res)

@app.route('/api/logs', methods=['GET'])
def api_raw_logs():
    limit = int(request.args.get('limit', 100))
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM raw_logs ORDER BY id DESC LIMIT ?", (limit,))
    rows = [dict(row) for row in cursor.fetchall()]
    conn.close()
    return jsonify(rows)

@app.route('/api/settings', methods=['GET', 'POST'])
def api_settings():
    if request.method == 'POST':
        data = request.json or {}
        if 'groq_api_key' in data:
            set_setting('groq_api_key', data['groq_api_key'].strip())
        if 'groq_model' in data:
            set_setting('groq_model', data['groq_model'])
        if 'simulator_enabled' in data:
            val = bool(data['simulator_enabled'])
            ingestion_engine.simulator_enabled = val
            set_setting('simulator_enabled', 'true' if val else 'false')
        return jsonify({"success": True, "message": "Settings updated."})
    else:
        key = get_setting('groq_api_key', '')
        # Mask key for privacy
        masked_key = (key[:6] + "..." + key[-4:]) if len(key) > 10 else ("Configured" if key else "")
        return jsonify({
            "groq_api_key_set": bool(key),
            "groq_api_key_masked": masked_key,
            "groq_model": get_setting('groq_model', AVAILABLE_MODELS[0]),
            "simulator_enabled": ingestion_engine.simulator_enabled
        })

@app.route('/api/simulate', methods=['POST'])
def api_trigger_simulate():
    data = request.json or {}
    scenario_type = data.get('type', 'random')
    
    if scenario_type == 'sqli':
        event = ingestion_engine.process_log("WebServer-DMZ", "CRITICAL", "HTTP POST /login?id=1'%20UNION%20SELECT%20username,password%20FROM%20users-- from IP 192.168.1.205")
    elif scenario_type == 'powershell':
        event = ingestion_engine.process_log("Workstation-HR", "CRITICAL", "powershell.exe -ExecutionPolicy Bypass -enc SQBFAFgAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAAp")
    elif scenario_type == 'bruteforce':
        for _ in range(4):
            ingestion_engine.process_log("AuthServer-01", "WARN", "Failed password for user root from 203.0.113.88 port 22 ssh2")
        event = ingestion_engine.process_log("AuthServer-01", "CRITICAL", "Failed password for user root from 203.0.113.88 port 22 ssh2")
    else:
        event = ingestion_engine.process_log("Firewall-Core", "CRITICAL", "Unauthorized privilege escalation attempted: EventID 4728 Domain Admins modified by IP 10.0.1.50")
        
    return jsonify({"success": True, "triggered_event": event})

@app.route('/api/stream/events')
def api_stream_events():
    """SSE endpoint for streaming live events & logs to dashboard."""
    def event_stream():
        q = queue.Queue()

        def listener_callback(event_data, log_data):
            q.put({"event": event_data, "log": log_data})

        register_listener(listener_callback)
        try:
            yield "data: {\"type\": \"connected\"}\n\n"
            while True:
                try:
                    data = q.get(timeout=25)
                    metrics = get_soc_metrics()
                    payload = {
                        "type": "update",
                        "metrics": metrics,
                        "event": data.get("event"),
                        "log": data.get("log")
                    }
                    yield f"data: {json.dumps(payload)}\n\n"
                except queue.Empty:
                    # Heartbeat
                    yield "data: {\"type\": \"ping\"}\n\n"
        finally:
            unregister_listener(listener_callback)

    return Response(event_stream(), mimetype='text/event-stream')

if __name__ == '__main__':
    print("=========================================================")
    print(" [+] SOC Security Operations Center AI Dashboard Starting")
    print(" Access UI at: http://127.0.0.1:5000")
    print("=========================================================")
    app.run(host='0.0.0.0', port=5000, debug=False)
